version: '3.3'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: vesnushka-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    postgres:
        image: postgres:15
        container_name: vesnushka-postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: bot
            POSTGRES_USER: bot
            POSTGRES_PASSWORD: bot
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data

    php:
        container_name: vesnushka-php
        restart: unless-stopped
        build: docker/php
        volumes:
            - ./app:/var/www/html
        depends_on:
            - postgres
